#!/bin/bash
source /usr/share/yunohost/helpers
source _common.sh

app=$1
domain=$2

installedDomain=$(ynh_app_setting_get $app domain)
if [ "$domain" == "$installedDomain" ];then
   update_ca_cert
fi
