#!/bin/bash
source /usr/share/yunohost/helpers
source ../apps/openvpn/scripts/_common.sh

updatedDomain=$1

export domain=$(ynh_app_setting_get $app domain)

if [ "$domain" == "$updatedDomain" ];then
   export app=openvpn
   export local_path=/var/www/$app
   export ta_key=$(sudo cat /etc/openvpn/ta.key)
   export port=$(ynh_app_setting_get $app port)
   update_ca_cert
   systemctl openvpn restart
fi
